services:
  movies:
    build: .
    ports:
      - "8080:8080"
    depends_on:
     - elasticsearch
#       condition: service_healthy
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
#    volumes:
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    #  - node.name=es01
    #  - cluster.name=docker-cluster
    ports:
      - "9200:9200"
    networks:
      - elastic
   # healthcheck:
   #   test: [ "CMD", "curl", "-f", "http://elasticsearch:9200" ]
   #   interval: 30s
   #   timeout: 10s
   #   retries: 5

networks:
  elastic:
    driver: bridge
