services:
  market:
    build: .
    ports:
      - "8080:8080"
    depends_on:
     - elasticsearch
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
    ports:
      - "9200:9200"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge